<?php

/**
 * Developed by eBrook Group.
 * Copyright © 2026 eBrook Group (https://www.ebrook.com.tw)
 */

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\AchievementTemplate;
use Illuminate\Database\Seeder;

class AchievementTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // ========== 消费类成就（金额） ==========
            [
                'name' => '首次消费',
                'description' => '完成首次订单，开启美食之旅',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 1],
                'reward_points' => 100,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '消费新星',
                'description' => '累计消费达到500元，成为消费新星',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 500],
                'reward_points' => 200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => '消费达人',
                'description' => '累计消费达到1000元，享受更多优惠',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 1000],
                'reward_points' => 500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => '消费精英',
                'description' => '累计消费达到2000元，成为消费精英',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 2000],
                'reward_points' => 800,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => '消费专家',
                'description' => '累计消费达到3000元，成为消费专家',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 3000],
                'reward_points' => 1200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => '消费大师',
                'description' => '累计消费达到5000元，成为消费大师',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 5000],
                'reward_points' => 2000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '消费王者',
                'description' => '累计消费达到10000元，成为消费王者',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 10000],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => '消费传奇',
                'description' => '累计消费达到20000元，成为消费传奇',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 20000],
                'reward_points' => 10000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => '消费至尊',
                'description' => '累计消费达到50000元，成为消费至尊',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 50000],
                'reward_points' => 25000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => '消费神话',
                'description' => '累计消费达到100000元，成为消费神话',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 100000],
                'reward_points' => 50000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => '消费传说',
                'description' => '累计消费达到200000元，成为消费传说',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['amount' => 200000],
                'reward_points' => 100000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],

            // ========== 消费类成就（订单数） ==========
            [
                'name' => '订单新手',
                'description' => '累计完成3笔订单，开启订单之旅',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 3],
                'reward_points' => 150,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => '订单达人',
                'description' => '累计完成10笔订单，成为订单达人',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 10],
                'reward_points' => 300,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => '订单精英',
                'description' => '累计完成20笔订单，成为订单精英',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 20],
                'reward_points' => 600,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => '订单专家',
                'description' => '累计完成30笔订单，成为订单专家',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 30],
                'reward_points' => 1000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => '订单大师',
                'description' => '累计完成50笔订单，成为订单大师',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 50],
                'reward_points' => 1500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => '订单王者',
                'description' => '累计完成100笔订单，成为订单王者',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 100],
                'reward_points' => 3000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => '订单传奇',
                'description' => '累计完成200笔订单，成为订单传奇',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 200],
                'reward_points' => 6000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => '订单至尊',
                'description' => '累计完成500笔订单，成为订单至尊',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 500],
                'reward_points' => 15000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => '订单神话',
                'description' => '累计完成1000笔订单，成为订单神话',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 1000],
                'reward_points' => 30000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => '订单传说',
                'description' => '累计完成2000笔订单，成为订单传说',
                'icon' => null,
                'category' => 'consume',
                'target_value' => ['count' => 2000],
                'reward_points' => 60000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 19,
            ],

            // ========== 评价类成就 ==========
            [
                'name' => '评价新手',
                'description' => '完成3次评价，分享您的用餐体验',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 3],
                'reward_points' => 100,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '评价达人',
                'description' => '完成5次评价，成为评价达人',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 5],
                'reward_points' => 200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => '评价精英',
                'description' => '完成10次评价，成为评价精英',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 10],
                'reward_points' => 400,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => '评价专家',
                'description' => '完成20次评价，成为评价专家',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 20],
                'reward_points' => 800,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => '评价大师',
                'description' => '完成50次评价，成为评价大师',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 50],
                'reward_points' => 2000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => '评价王者',
                'description' => '完成100次评价，成为评价王者',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 100],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '评价传奇',
                'description' => '完成200次评价，成为评价传奇',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 200],
                'reward_points' => 10000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => '评价至尊',
                'description' => '完成300次评价，成为评价至尊',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 300],
                'reward_points' => 20000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => '评价神话',
                'description' => '完成500次评价，成为评价神话',
                'icon' => null,
                'category' => 'review',
                'target_value' => ['count' => 500],
                'reward_points' => 50000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],

            // ========== 邀请类成就 ==========
            [
                'name' => '邀请新手',
                'description' => '邀请1位好友注册，获得邀请奖励',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 1],
                'reward_points' => 200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '邀请达人',
                'description' => '邀请3位好友注册，成为邀请达人',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 3],
                'reward_points' => 600,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => '邀请精英',
                'description' => '邀请5位好友注册，成为邀请精英',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 5],
                'reward_points' => 1000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => '邀请专家',
                'description' => '邀请7位好友注册，成为邀请专家',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 7],
                'reward_points' => 1500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => '邀请大师',
                'description' => '邀请10位好友注册，成为邀请大师',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 10],
                'reward_points' => 2500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => '邀请王者',
                'description' => '邀请15位好友注册，成为邀请王者',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 15],
                'reward_points' => 4000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '邀请传奇',
                'description' => '邀请20位好友注册，成为邀请传奇',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 20],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => '邀请至尊',
                'description' => '邀请30位好友注册，成为邀请至尊',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 30],
                'reward_points' => 8000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => '邀请神话',
                'description' => '邀请50位好友注册，成为邀请神话',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 50],
                'reward_points' => 15000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => '邀请至尊',
                'description' => '邀请100位好友注册，成为邀请至尊',
                'icon' => null,
                'category' => 'invite',
                'target_value' => ['count' => 100],
                'reward_points' => 30000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],

            // ========== 签到类成就（累计签到） ==========
            [
                'name' => '签到新手',
                'description' => '累计签到3天，养成签到习惯',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 3],
                'reward_points' => 50,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '签到达人',
                'description' => '累计签到7天，成为签到达人',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 7],
                'reward_points' => 100,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => '签到精英',
                'description' => '累计签到14天，成为签到精英',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 14],
                'reward_points' => 200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => '签到专家',
                'description' => '累计签到30天，成为签到专家',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 30],
                'reward_points' => 500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => '签到大师',
                'description' => '累计签到60天，成为签到大师',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 60],
                'reward_points' => 1000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => '签到王者',
                'description' => '累计签到100天，成为签到王者',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 100],
                'reward_points' => 2000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '签到传奇',
                'description' => '累计签到180天，成为签到传奇',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 180],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => '签到至尊',
                'description' => '累计签到365天，成为签到至尊',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 365],
                'reward_points' => 10000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => '签到神话',
                'description' => '累计签到500天，成为签到神话',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 500],
                'reward_points' => 20000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => '签到传说',
                'description' => '累计签到1000天，成为签到传说',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['days' => 1000],
                'reward_points' => 50000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],

            // ========== 签到类成就（连续签到） ==========
            [
                'name' => '连续签到3天',
                'description' => '连续签到3天，保持良好习惯',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 3],
                'reward_points' => 50,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => '连续签到7天',
                'description' => '连续签到7天，一周坚持',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 7],
                'reward_points' => 150,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => '连续签到14天',
                'description' => '连续签到14天，两周坚持',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 14],
                'reward_points' => 300,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => '连续签到王',
                'description' => '连续签到30天，成为连续签到王',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 30],
                'reward_points' => 1000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => '连续签到60天',
                'description' => '连续签到60天，两个月坚持',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 60],
                'reward_points' => 2500,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => '连续签到90天',
                'description' => '连续签到90天，三个月坚持',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 90],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => '连续签到180天',
                'description' => '连续签到180天，半年坚持',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 180],
                'reward_points' => 10000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => '连续签到365天',
                'description' => '连续签到365天，一年坚持，毅力非凡',
                'icon' => null,
                'category' => 'checkin',
                'target_value' => ['consecutive_days' => 365],
                'reward_points' => 20000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 16,
            ],

            // ========== 积分类成就 ==========
            [
                'name' => '积分新手',
                'description' => '累计获得500积分，开启积分之旅',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 500],
                'reward_points' => 100,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '积分达人',
                'description' => '累计获得1000积分，成为积分达人',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 1000],
                'reward_points' => 200,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => '积分精英',
                'description' => '累计获得2000积分，成为积分精英',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 2000],
                'reward_points' => 400,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => '积分专家',
                'description' => '累计获得5000积分，成为积分专家',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 5000],
                'reward_points' => 800,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => '积分大师',
                'description' => '累计获得10000积分，成为积分大师',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 10000],
                'reward_points' => 1000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => '积分王者',
                'description' => '累计获得20000积分，成为积分王者',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 20000],
                'reward_points' => 2000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '积分传奇',
                'description' => '累计获得50000积分，成为积分传奇',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 50000],
                'reward_points' => 5000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => '积分至尊',
                'description' => '累计获得100000积分，成为积分至尊',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 100000],
                'reward_points' => 10000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => '积分神话',
                'description' => '累计获得200000积分，成为积分神话',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 200000],
                'reward_points' => 20000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => '积分至尊',
                'description' => '累计获得300000积分，成为积分至尊',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 300000],
                'reward_points' => 30000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => '积分传说',
                'description' => '累计获得500000积分，成为积分传说',
                'icon' => null,
                'category' => 'points',
                'target_value' => ['total_points' => 500000],
                'reward_points' => 50000,
                'reward_coupon_id' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
        ];

        foreach ($templates as $templateData) {
            AchievementTemplate::updateOrCreate(
                [
                    'name' => $templateData['name'],
                    'category' => $templateData['category'],
                ],
                $templateData
            );
        }

        $this->command->info('成就模板已创建！共 ' . count($templates) . ' 个成就模板');
    }
}
